id: ICB303CC4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T22:50:23+00:00'
last_modified: '2022-06-15T17:29:33.603650+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG18533
  title: དཀར་ཟས་རིང་ལུགས་ཀྱི་ཕན་ཡོན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    D933:
      image_group_id: I1KG18560
      title: Volume 1 of dkar zas ring lugs kyi phan yon/
      total_pages: 108
      order: 1
      base_file: D933.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
